const szavak = [
  {"evfolyam":1,"szo":"Gergely","szotagok_szama":2,"szofaj":"tulajdonnév","peldamondat":"Gergely ma korán kelt.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":1,"szo":"Ibolya","szotagok_szama":3,"szofaj":"főnév / tulajdonnév","peldamondat":"Az ibolya illatos virág.","helyes_betu":"ly","megjegyzes":"többjelentésű: név is"},
  {"evfolyam":1,"szo":"Mihály","szotagok_szama":2,"szofaj":"tulajdonnév","peldamondat":"Mihály rajzot készít.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":1,"szo":"ajtó","szotagok_szama":2,"szofaj":"főnév","peldamondat":"Az ajtó csukva van.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"fej","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A fejem fáj egy kicsit.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"gólya","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A gólya fészket rak a kéményen.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":1,"szo":"haj","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A hajamat megfésültem.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"jég","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A jég hideg és csúszós.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"játék","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A játék az asztalon van.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"jármű","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A bicikli egy jármű.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"jön","szotagok_szama":1,"szofaj":"ige","peldamondat":"A busz hamarosan jön.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"jó","szotagok_szama":1,"szofaj":"melléknév","peldamondat":"Ez egy jó ötlet.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"juh","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A juh béget a legelőn.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"királyfi","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A királyfi elindult szerencsét próbálni.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":1,"szo":"lyuk","szotagok_szama":1,"szofaj":"főnév","peldamondat":"Lyuk van a zoknin.","helyes_betu":"ly","megjegyzes":"az egyetlen ly-kezdetű közszó"},
  {"evfolyam":1,"szo":"lyukas","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"A labda lyukas.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":1,"szo":"rajz","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A rajz a falon lóg.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"tej","szotagok_szama":1,"szofaj":"főnév","peldamondat":"Reggel tejet ittam.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"ujj","szotagok_szama":1,"szofaj":"főnév","peldamondat":"Megvágtam az ujjamat.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"új","szotagok_szama":1,"szofaj":"melléknév","peldamondat":"Új füzetet vettem.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"vaj","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A kenyérre vajat kentem.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":1,"szo":"zaj","szotagok_szama":1,"szofaj":"főnév","peldamondat":"Nagy zaj volt az udvaron.","helyes_betu":"j","megjegyzes":""},

  {"evfolyam":2,"szo":"bagoly","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Éjjel huhog a bagoly.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"bója","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A bója a vízben lebeg.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"borjú","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A borjú az istállóban pihen.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"csekély","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"Csekély volt a különbség.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"éj","szotagok_szama":1,"szofaj":"főnév","peldamondat":"Az éj csendes volt.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"éjjel","szotagok_szama":2,"szofaj":"határozószó","peldamondat":"Éjjel sokat esett az eső.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"fej","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A fejem fáj egy kicsit.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"foly","szotagok_szama":1,"szofaj":"ige","peldamondat":"A patak gyorsan foly.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"folyik","szotagok_szama":2,"szofaj":"ige","peldamondat":"A víz a csapból folyik.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"folyó","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A folyó a város mellett kanyarog.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"folyosó","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A folyosó végén van a terem.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"furulya","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Furulyán játszott az osztályban.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"gally","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A tűzre gallyat gyűjtöttünk.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"golyó","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A gyerek elgurította a golyót.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"hajó","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A hajó kikötött a parton.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"héj","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A tojás héja eltört.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"hely","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A hely a padban az enyém.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"joghurt","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A joghurt hideg desszert.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"karéj","szotagok_szama":2,"szofaj":"főnév","peldamondat":"Egy karéj kenyeret kért.","helyes_betu":"j","megjegyzes":"j-vel írandó"},
  {"evfolyam":2,"szo":"kályha","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A kályha meleget ad.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"lakáj","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A mesében a lakáj szolgál.","helyes_betu":"j","megjegyzes":"j-vel írandó kivétel"},
  {"evfolyam":2,"szo":"mély","szotagok_szama":1,"szofaj":"melléknév","peldamondat":"Mély a gödör.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"moly","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A moly kilyukaszthatja a ruhát.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"muszáj","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"Muszáj sietnünk.","helyes_betu":"j","megjegyzes":"j-vel írandó, gyakori tévesztés"},
  {"evfolyam":2,"szo":"osztály","szotagok_szama":2,"szofaj":"főnév","peldamondat":"Az osztály kirándulni megy.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"papagáj","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A papagáj utánozza a hangokat.","helyes_betu":"j","megjegyzes":"j-vel írandó kivétel"},
  {"evfolyam":2,"szo":"rejtvény","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A rejtvényt együtt fejtettük meg.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"sajt","szotagok_szama":1,"szofaj":"főnév","peldamondat":"Sajtot tettem a szendvicsbe.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"súly","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A táska súlya nagy.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":2,"szo":"talaj","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A talaj nedves eső után.","helyes_betu":"j","megjegyzes":"j-vel írandó kivétel"},
  {"evfolyam":2,"szo":"tojás","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A tojásból rántottát készítettem.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"varjú","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A varjú a fa tetején ült.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":2,"szo":"zsivaj","szotagok_szama":2,"szofaj":"főnév","peldamondat":"Zsivaj volt a játszótéren.","helyes_betu":"j","megjegyzes":""},

  {"evfolyam":3,"szo":"ajándék","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Ajándékot adott a barátjának.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":3,"szo":"akadály","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Egy akadály állt az útban.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"amely","szotagok_szama":2,"szofaj":"névmás","peldamondat":"Az a ház, amelyik a sarkon áll, régi.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"amelyik","szotagok_szama":3,"szofaj":"névmás","peldamondat":"Amelyik gyerek kész, jelentkezzen.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"csekély","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"Csekély volt a különbség.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"ilyen","szotagok_szama":2,"szofaj":"névmás","peldamondat":"Ilyen feladatot már oldottunk.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"ily","szotagok_szama":1,"szofaj":"névmás","peldamondat":"Ilyen nap ritkán van.","helyes_betu":"ly","megjegyzes":"alakváltozat: ilyen"},
  {"evfolyam":3,"szo":"jutalom","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A jutalom egy matrica volt.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":3,"szo":"kastély","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A kastélyt sok turista látogatja.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"kevély","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"Kevélyen nézett körül.","helyes_betu":"ly","megjegyzes":"ritkább, választékos"},
  {"evfolyam":3,"szo":"király","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A király a trónon ült.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"komoly","szotagok_szama":3,"szofaj":"melléknév","peldamondat":"Komoly munkát végzett.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"kristály","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A kristály a napfényben csillog.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"mely","szotagok_szama":1,"szofaj":"névmás","peldamondat":"Az a kérdés, mely a fontosabb.","helyes_betu":"ly","megjegyzes":"homográf: többféle viszonyító"},
  {"evfolyam":3,"szo":"melyik","szotagok_szama":2,"szofaj":"névmás","peldamondat":"Melyik ceruza a tiéd?","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"mily","szotagok_szama":1,"szofaj":"névmás","peldamondat":"Mily szép ez a kép!","helyes_betu":"ly","megjegyzes":"változat: milyen"},
  {"evfolyam":3,"szo":"milyen","szotagok_szama":2,"szofaj":"névmás","peldamondat":"Milyen idő lesz holnap?","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"oly","szotagok_szama":1,"szofaj":"névmás","peldamondat":"Oly csend lett hirtelen.","helyes_betu":"ly","megjegyzes":"alakváltozat: olyan"},
  {"evfolyam":3,"szo":"olyan","szotagok_szama":2,"szofaj":"névmás","peldamondat":"Olyan könyvet keresek, ami érdekes.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"rejtély","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A történet egy rejtéllyel kezdődött.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"sekély","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"A tó itt sekély.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"selymes","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"Selymes tapintású volt az anyag.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"személy","szotagok_szama":2,"szofaj":"főnév","peldamondat":"Egy ismeretlen személy kopogott.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"szabály","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A szabályokat be kell tartani.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"tartály","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A tartály tele van vízzel.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":3,"szo":"ünnepély","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Az iskolában ünnepélyt tartottunk.","helyes_betu":"ly","megjegyzes":""},

  {"evfolyam":4,"szo":"befolyás","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A reklámnak nagy a befolyása.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"befolyásol","szotagok_szama":4,"szofaj":"ige","peldamondat":"A döntést sok dolog befolyásolja.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"befolyásos","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"Befolyásos emberrel találkozott.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"fekhely","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A kutya a fekhelyén alszik.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"folyam","szotagok_szama":2,"szofaj":"főnév","peldamondat":"Részt vett egy nyári tanfolyamon.","helyes_betu":"ly","megjegyzes":"a 'folyam' szó többjelentésű"},
  {"evfolyam":4,"szo":"folyamat","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A tanulás hosszú folyamat.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"folyamatos","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"Folyamatos gyakorlás kell.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"folytat","szotagok_szama":2,"szofaj":"ige","peldamondat":"Holnap folytatjuk a munkát.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"folytatás","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A történet folytatása izgalmas.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"hajlandó","szotagok_szama":3,"szofaj":"melléknév","peldamondat":"Hajlandó volt segíteni.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":4,"szo":"hajlamos","szotagok_szama":3,"szofaj":"melléknév","peldamondat":"Hajlamos elfelejteni a határidőt.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":4,"szo":"hajlék","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A hajlék védelmet ad a hidegben.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":4,"szo":"hajléktalan","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"A hajléktalan ember segítséget kapott.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":4,"szo":"helyesírás","szotagok_szama":4,"szofaj":"főnév","peldamondat":"A helyesírás gyakorlása fontos.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"helyesen","szotagok_szama":3,"szofaj":"határozószó","peldamondat":"Helyesen írtad le a szót.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"helyszín","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A helyszínre megérkezett a mentő.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"helytelen","szotagok_szama":3,"szofaj":"melléknév","peldamondat":"Helytelen választ adtál.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"homály","szotagok_szama":2,"szofaj":"főnév","peldamondat":"Homály volt az erdőben.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"homályos","szotagok_szama":3,"szofaj":"melléknév","peldamondat":"Homályos lett a szemüvegem.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"műhely","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A műhelyben javítják a biciklit.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"pálya","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A sportpálya sáros volt.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"pályaudvar","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A pályaudvaron sokan várakoztak.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"süllyed","szotagok_szama":2,"szofaj":"ige","peldamondat":"A kő a vízben süllyed.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"süllyeszt","szotagok_szama":2,"szofaj":"ige","peldamondat":"Óvatosan a vízbe süllyesztette.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"súlyos","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"Súlyos a bőrönd.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"súlypont","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A súlypontot nehéz megtartani.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"súlytalan","szotagok_szama":3,"szofaj":"melléknév","peldamondat":"A holdon a test majdnem súlytalan.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"tűzhely","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A tűzhelyen forr a víz.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":4,"szo":"ujjong","szotagok_szama":2,"szofaj":"ige","peldamondat":"A közönség ujjongott a győzelem után.","helyes_betu":"j","megjegyzes":""},

  {"evfolyam":5,"szo":"bejegyzés","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A naplóban új bejegyzés van.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"bejelent","szotagok_szama":3,"szofaj":"ige","peldamondat":"Bejelentette a változást.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"bejelentés","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A bejelentés után csend lett.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jegyzet","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A jegyzet tele volt rajzokkal.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jel","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A táblán egy jel mutatta az irányt.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jelleg","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A feladatnak más a jellege.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jellegzetes","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"Jellegzetes illat terjengett.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jellem","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A jellem sokat számít.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jellemzés","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A könyv végén van jellemzés.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jellemző","szotagok_szama":3,"szofaj":"melléknév","peldamondat":"Ez a hiba rá jellemző.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jelzés","szotagok_szama":2,"szofaj":"főnév","peldamondat":"Piros jelzést kaptunk.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jelző","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A jelző színesíti a mondatot.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jártasság","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A jártasság gyakorlással fejlődik.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"járulék","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A fizetéshez járulék tartozik.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"járvány","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A járvány miatt elmaradt a program.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"javaslat","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Egy javaslatot tett.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"javasol","szotagok_szama":3,"szofaj":"ige","peldamondat":"Javaslom, hogy kezdjük el.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jövő","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A jövő még bizonytalan.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jövőbeli","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"A jövőbeli tervei nagyok.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jövedelem","szotagok_szama":4,"szofaj":"főnév","peldamondat":"A jövedelem hónapról hónapra változik.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":5,"szo":"jövendöl","szotagok_szama":3,"szofaj":"ige","peldamondat":"A mesében a jós jövendöl.","helyes_betu":"j","megjegyzes":"ritkább ige"},

  {"evfolyam":6,"szo":"báj","szotagok_szama":1,"szofaj":"főnév","peldamondat":"A mosolyának különös bája volt.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":6,"szo":"bájital","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A mesében bájitalt főztek.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":6,"szo":"feljegyzés","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Feljegyzést készített az órán.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":6,"szo":"folyamatos","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"Folyamatos gyakorlás kell.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":6,"szo":"folyóirat","szotagok_szama":4,"szofaj":"főnév","peldamondat":"A könyvtárban folyóiratot olvas.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":6,"szo":"helyi","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"A helyi újságban olvastam.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":6,"szo":"helyettes","szotagok_szama":3,"szofaj":"melléknév","peldamondat":"A tanár helyettes volt ma.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":6,"szo":"helyettesít","szotagok_szama":3,"szofaj":"ige","peldamondat":"Ma ő helyettesíti a tanárt.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":6,"szo":"kijavít","szotagok_szama":3,"szofaj":"ige","peldamondat":"Kijavította a hibát.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":6,"szo":"kijelentés","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A kijelentés nem volt igaz.","helyes_betu":"j","megjegyzes":""},

  {"evfolyam":7,"szo":"hajózási","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"Hajózási tilalmat rendeltek el.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"hajós","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A hajós a fedélzeten dolgozott.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"helyiség","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A helyiség ajtaját bezárták.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":7,"szo":"jellegzetes","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"Jellegzetes illat terjengett.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"jelentés","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Jelentést írt a kísérletről.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"jelentéstan","szotagok_szama":4,"szofaj":"főnév","peldamondat":"A jelentéstan a jelentéssel foglalkozik.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"jogos","szotagok_szama":2,"szofaj":"melléknév","peldamondat":"Jogos volt a kérdés.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"jogellenes","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"Jogellenes volt a döntés.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"jogállam","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A jogállam alapelveit tanulták.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"jogász","szotagok_szama":2,"szofaj":"főnév","peldamondat":"A jogász tanácsot adott.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"jogkövető","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"Jogkövető magatartást várnak el.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"jogosítvány","szotagok_szama":4,"szofaj":"főnév","peldamondat":"Megszerezte a jogosítványt.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":7,"szo":"jogszabály","szotagok_szama":3,"szofaj":"főnév","peldamondat":"A jogszabályt be kell tartani.","helyes_betu":"j","megjegyzes":""},

  {"evfolyam":8,"szo":"amellyel","szotagok_szama":3,"szofaj":"névmás","peldamondat":"Az eszköz, amellyel dolgozunk, pontos.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":8,"szo":"egyáltalán","szotagok_szama":4,"szofaj":"határozószó","peldamondat":"Egyáltalán nem így gondoltam.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":8,"szo":"helyesbítés","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Kértem egy helyesbítést.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":8,"szo":"helyesírás-ellenőrzés","szotagok_szama":7,"szofaj":"főnév","peldamondat":"Bekapcsoltam a helyesírás-ellenőrzést.","helyes_betu":"ly","megjegyzes":"összetétel; kötőjelhasználat kontextusfüggő"},
  {"evfolyam":8,"szo":"helyesírási","szotagok_szama":5,"szofaj":"melléknév","peldamondat":"A helyesírási hibákat kijavítottuk.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":8,"szo":"helyreigazítás","szotagok_szama":5,"szofaj":"főnév","peldamondat":"A cikkhez helyreigazítást kértek.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":8,"szo":"kijelentő","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"A kijelentő mondatot felismerte.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":8,"szo":"kijelentőmód","szotagok_szama":4,"szofaj":"főnév","peldamondat":"A kijelentőmód a leggyakoribb mód.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":8,"szo":"körülbelül","szotagok_szama":4,"szofaj":"határozószó","peldamondat":"Körülbelül tíz perc múlva jövök.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":8,"szo":"megbízható","szotagok_szama":4,"szofaj":"melléknév","peldamondat":"Megbízható forrásból tájékozódtunk.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":8,"szo":"megjegyzés","szotagok_szama":3,"szofaj":"főnév","peldamondat":"Egy megjegyzést fűzött hozzá.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":8,"szo":"megjegyzi","szotagok_szama":3,"szofaj":"ige","peldamondat":"A tanár megjegyzi a lényeget.","helyes_betu":"j","megjegyzes":""},
  {"evfolyam":8,"szo":"melyikük","szotagok_szama":3,"szofaj":"névmás","peldamondat":"Melyikük hozta el a könyvet?","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":8,"szo":"súlyosbodik","szotagok_szama":4,"szofaj":"ige","peldamondat":"A helyzet súlyosbodik.","helyes_betu":"ly","megjegyzes":""},
  {"evfolyam":8,"szo":"ugyanilyen","szotagok_szama":4,"szofaj":"névmás","peldamondat":"Ugyanilyen feladatot kaptunk tavaly.","helyes_betu":"ly","megjegyzes":""}
];

if (typeof window !== "undefined") { window.szavak = szavak; }

